// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoodenGardenServer.Data;

#nullable disable

namespace WoodenGardenServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211218234932_GardenHouseImageContainsBase64Image")]
    partial class GardenHouseImageContainsBase64Image
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WoodenGardenApp.Shared.Models.Database.GardenHouse.GardenHouseImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GardenHouseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GardenHouseId");

                    b.ToTable("GardenHouseImageModels");
                });

            modelBuilder.Entity("WoodenGardenApp.Shared.Models.Database.GardenHouse.GardenHouseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GardenHouseModels");
                });

            modelBuilder.Entity("WoodenGardenApp.Shared.Models.Database.GardenHouse.GardenHouseImageModel", b =>
                {
                    b.HasOne("WoodenGardenApp.Shared.Models.Database.GardenHouse.GardenHouseModel", "GardenHouse")
                        .WithMany("GardenHouseImages")
                        .HasForeignKey("GardenHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GardenHouse");
                });

            modelBuilder.Entity("WoodenGardenApp.Shared.Models.Database.GardenHouse.GardenHouseModel", b =>
                {
                    b.Navigation("GardenHouseImages");
                });
#pragma warning restore 612, 618
        }
    }
}
