//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodenGardenFront.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoodenGardenFront.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file. File name empty..
        /// </summary>
        internal static string Client_FileUpload_DeleteFileNameEmpty {
            get {
                return ResourceManager.GetString("Client_FileUpload_DeleteFileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not upload file. File extension not supported..
        /// </summary>
        internal static string Client_FileUpload_FileExtensionNotSupported {
            get {
                return ResourceManager.GetString("Client_FileUpload_FileExtensionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not upload file. File name empty..
        /// </summary>
        internal static string Client_FileUpload_FileNameEmpty {
            get {
                return ResourceManager.GetString("Client_FileUpload_FileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not upload file. Error occured while saving..
        /// </summary>
        internal static string Client_FileUpload_FileNotAdded {
            get {
                return ResourceManager.GetString("Client_FileUpload_FileNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file. Error occured while removing file..
        /// </summary>
        internal static string Client_FileUpload_FileNotDeletedError {
            get {
                return ResourceManager.GetString("Client_FileUpload_FileNotDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file. File not exists..
        /// </summary>
        internal static string Client_FileUpload_FileToDeleteNotExists {
            get {
                return ResourceManager.GetString("Client_FileUpload_FileToDeleteNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete image. Error occured..
        /// </summary>
        internal static string Client_GardenHouseImageService_DeleteImagesException {
            get {
                return ResourceManager.GetString("Client_GardenHouseImageService_DeleteImagesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add image. Image not provided..
        /// </summary>
        internal static string Client_GardenHouseImageService_ImageBase64NotProvided {
            get {
                return ResourceManager.GetString("Client_GardenHouseImageService_ImageBase64NotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add image. Api returned error..
        /// </summary>
        internal static string Client_GardenHouseImageService_ResponseErrorImageNotAdded {
            get {
                return ResourceManager.GetString("Client_GardenHouseImageService_ResponseErrorImageNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add image. Room id not provided..
        /// </summary>
        internal static string Client_GardenHouseImageService_RoomIdNotProvided {
            get {
                return ResourceManager.GetString("Client_GardenHouseImageService_RoomIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No garden houses found in database..
        /// </summary>
        internal static string Client_GardenHouseService_CouldNotGatherHouses {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_CouldNotGatherHouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get garden houses. Api error..
        /// </summary>
        internal static string Client_GardenHouseService_GetHousesError {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_GetHousesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden house id has to be provided correctly..
        /// </summary>
        internal static string Client_GardenHouseService_HouseIdNotProvided {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_HouseIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden house name has to be provided..
        /// </summary>
        internal static string Client_GardenHouseService_HouseNameNotProvided {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_HouseNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add garden house. Api communication error..
        /// </summary>
        internal static string Client_GardenHouseService_HouseNotAdded {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_HouseNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete garden house. Api communication error..
        /// </summary>
        internal static string Client_GardenHouseService_HouseNotDeleted {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_HouseNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update garden house. Api communication error..
        /// </summary>
        internal static string Client_GardenHouseService_HouseNotUpdated {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_HouseNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete images. Ids not provided..
        /// </summary>
        internal static string Client_GardenHouseService_ImageIdsToDeleteNotProvided {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_ImageIdsToDeleteNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update garden house. Either new name or new description have to be provided..
        /// </summary>
        internal static string Client_GardenHouseService_NameAndDescriptionToUpdateNotProvided {
            get {
                return ResourceManager.GetString("Client_GardenHouseService_NameAndDescriptionToUpdateNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete images. Api error..
        /// </summary>
        internal static string Client_GardenHouseServiceImage_ApiErrorImagesNotDeleted {
            get {
                return ResourceManager.GetString("Client_GardenHouseServiceImage_ApiErrorImagesNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add image. Error occured..
        /// </summary>
        internal static string Client_GardenHouseServiceImage_ImageNotAddedException {
            get {
                return ResourceManager.GetString("Client_GardenHouseServiceImage_ImageNotAddedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has to be provided in toastr..
        /// </summary>
        internal static string Client_ToastrHelper_MessageNotProvided {
            get {
                return ResourceManager.GetString("Client_ToastrHelper_MessageNotProvided", resourceCulture);
            }
        }
    }
}
