name: Release Server

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      shell: bash
      run: |
        # Define some variables for things we need
        tag=$(git describe --tags --abbrev=0)
        release_name="App-$tag-${{ matrix.target }}"

        # Build everything
        dotnet publish WoodenGardenApp/Server/WoodenGardenApp.Server.csproj --runtime "${{ matrix.target }}" -c Release -o "$release_name"
    
    - name: Create ef bundle
    shell: bash
    run: |
      # Create ef bundle
      if [ "${{ matrix.target }}" == "win-x64" ]; then
        dotnet ef migartions bundle --configuration Bundle --project WoodenGardenApp/Server/WoodenGardenApp.Server.csproj -o "$release_name" --self-contained
      else
        dotnet ef migrations bundle --project WoodenGardenApp/Server/WoodenGardenApp.Server.csproj --verbose -o "$release_name" --self-contained
      fi

    - name: Pack files
      shell: bash
      run: |
        # Pack files
        if [ "${{ matrix.target }}" == "win-x64" ]; then
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
        else
          tar czvf "${release_name}.tar.gz" "$release_name"
        fi
      
    - name: Delete output dir
      shell: bash
      run: |
        # Delete output directory
        rm -r "$release_name"
        
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "App*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
